### ISSUE TITLE
cargo test fail on failing_alternate_backend

### ISSUE THREAD

**Issue by kazuk** [rust-lang-nursery/mdBook#671]
I fork and clone this repo.

cargo build is successfull with 1 warning.
cargo test fail on failing_alternate_backend.

this test pass normaly? 

```
PS C:\dev\mdBook> cargo test --test alternate_backends
    Finished dev [unoptimized + debuginfo] target(s) in 0.62 secs
     Running target\debug\deps\alternate_backends-e3b04d53d0b18fff.exe

running 4 tests
test missing_backends_arent_fatal ... ok
test alternate_backend_with_arguments ... ok
test passing_alternate_backend ... ok
test failing_alternate_backend ... FAILED

failures:

---- failing_alternate_backend stdout ----
        thread 'failing_alternate_backend' panicked at 'called `Result::unwrap_err()` on an `Ok` value: ()', src\libcore\result.rs:916:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:56
   2: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:381
   3: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:577
   5: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   7: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:498
   8: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   9: core::result::unwrap_failed<()>
             at C:\projects\rust\src\libcore\macros.rs:23
  10: core::result::Result<(), mdbook::errors::Error>::unwrap_err<(),mdbook::errors::Error>
             at C:\projects\rust\src\libcore\result.rs:841
  11: alternate_backends::failing_alternate_backend
             at .\tests\alternate_backends.rs:23
  12: alloc::boxed::{{impl}}::call_box<(),closure>
             at C:\projects\rust\src\liballoc\boxed.rs:815
  13: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:101


failures:
    failing_alternate_backend

test result: FAILED. 3 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test alternate_backends'
PS C:\dev\mdBook>
```

I run cargo test on Windows 10 with rustc 1.24.1 / cargo 0.25.0, 

```
PS C:\dev\mdBook> rustc --version
rustc 1.24.1 (d3ae9a9e0 2018-02-27)
PS C:\dev\mdBook> cargo --version
cargo 0.25.0 (96d8071da 2018-02-26)
PS C:\dev\mdBook>
```

**Comment by mattico** [comment]
Works fine on my machine.

```
D:\Code\Rust\mdbook (master -> origin)
λ rustc --version
rustc 1.24.1 (d3ae9a9e0 2018-02-27)

D:\Code\Rust\mdbook (master -> origin)
λ cargo test --test alternate_backends
    Finished dev [unoptimized + debuginfo] target(s) in 0.1 secs
     Running target\debug\deps\alternate_backends-e3b04d53d0b18fff.exe

running 4 tests
Hello World!
test missing_backends_arent_fatal ... ok
test passing_alternate_backend ... ok
test alternate_backend_with_arguments ... ok
test failing_alternate_backend ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by kazuk** [comment]
thanks , I will test with other machine.

**Comment by azerupi** [comment]
I have had this test fail on me too when working on a PR recently. I am not sure why and how, but it started passing again when I continued working on the code.

If other reports come in about this test, we should investigate the cause. In the mean time, I wouldn't worry too much about it. @kazuk Thanks for the report !

**Comment by Michael-F-Bryan** [comment]
These tests rely on having a couple "common" programs installed on the local system (`true`, `false`, and `echo`) because we use them to simulate a backend with a specific return code. 

When I originally wrote the tests I was using a Linux machine so the commands being executed are actual executables (e.g. `/bin/true`). Does Windows have similar programs installed, or are `true`, `false`, and `echo` built into the shell? I know Windows has a `where` program for locating files, @kazuk what do you get when you execute `where true`? And do you get similar results in both `cmd.exe` and powershell?

**Comment by azerupi** [comment]
`true` and `false` do not exist on Windows. `echo` does but it seems to have a different behavior in `cmd.exe` and powershell.

Would it be easy to rewrite the test(s) to not rely on those tools? Otherwise we can simply `cfg` them so that they get only run on *Unix*-like platforms.

**Comment by mattico** [comment]
Ah that explains it. I have the git shell exes in my PATH:
```
D:\Code
λ where true
C:\Program Files\Git\usr\bin\true.exe
```

**Comment by kazuk** [comment]
thanks, I try to find `true`, `false` in my machine.
and found it in git bash binaries `c:¥Program Files¥Git¥usr¥bin¥`

add PATH to it,  test `failing_alternate_backend` successful result.
